### ISSUE TITLE
button reset

### ISSUE THREAD

**Issue by dharapvj** [mirego/simple-css-reset#15]
Hi,

can I understand rationale behind the button reset?

Button reset completely strips off the button's background, border and makes indistinguishable. IMO, the reset should ensure that it looks same across the browser but at least it should look like a button.

Can you provide your thoughts?

**Comment by remi** [comment]
Hi @dharapvj,

We’ve created `simple-css-reset` so that we could use it as a basis for all of our Web projects at @mirego. In all of those projects, buttons look visually different, so we want to be able to style them from nothing when we start a new project.

For example, if we were to include borders for buttons in `simple-css-reset`, in half of our projects we’d have to remove them. In the other half, we’d have change them. Same thing for background colors.

So we chose to remove them completely in `simple-css-reset` to give us a clean slate 😄
